### PR TITLE
Updated logo and some images of TCET Linux

### LINKED ISSUE #40: [UPD] Logo, Images Checksum and iso link of TCET Linux
- [x] Updated TCET Linux logo
- [x] Updated images of installer

### PR DESCRIPTION
**Pull request by Akash6222**
## Title :
Updated logo and some images of TCET Linux

## Issue no : 
#40 

## Description
Title is enough

## Screenshots (if applicable)
NA

## Checklist
- [x] I have read and agree to abide by the [Code of Conduct](https://github.com/tcet-opensource/.github/blob/main/CODE_OF_CONDUCT.md)
- [x] I have read and followed the **Contributing Guidelines**

### CODE REVIEW

**Review by vish-rt — APPROVED** [review]

**Comment by vish-rt** [comment]
@kamalika0363 are these changes visually appealing and not like.. terrible

**Review by kamalika0363 — APPROVED** [review]
Visually Appealing I'd Say!!!

**Comment by kamalika0363** [comment]
> @kamalika0363 are these changes visually appealing and not like.. terrible

approvedddd!!!😤

**Comment by Akash6222** [comment]
@kamalika0363 wait for 20 min I have some more changes to don

**Pull request merged**
